primary_columns:
    fiyat: Float
    m2_brutfiyat: Float
    m2_brut: Float
    m2_net: Float
    aidat_tl: Float
    oda_sayisi: Integer
    bina_yasi: Integer
    bulundugu_kat: Integer
    kat_sayisi: Integer
    cat1: String
    cat2: String
    cat3: String
    cat4: String
    cat0: String
    loc1: String
    loc2: String
    loc3: String
    loc4: String
    loc5: String
    lat: String
    lon: String
    
secondary_columns: 
  - isitma
  - banyo_sayisi
  - balkon
  - esyali
  - kullanim_durumu
  - site_icerisinde
  - site_adi
  - krediye_uygun
  - tapu_durumu
  - kimden
  - goruntulu_arama_ile_gezilebilir
  - ilan_aks
  - Batı
  - Doğu
  - Güney
  - Kuzey
  - ADSL
  - Ahşap Doğrama
  - Akıllı Ev
  - Alarm (Hırsız)
  - Alarm (Yangın)
  - Alaturka Tuvalet
  - Alüminyum Doğrama
  - Amerikan Kapı
  - Amerikan Mutfak
  - Ankastre Fırın
  - Asansör
  - Barbekü
  - Beyaz Eşya
  - Boyalı
  - Bulaşık Makinesi
  - Buzdolabı
  - Çamaşır Kurutma Makinesi
  - Çamaşır Makinesi
  - Çamaşır Odası
  - Çelik Kapı
  - Duşakabin
  - Duvar Kağıdı
  - Ebeveyn Banyosu
  - Fırın
  - Fiber İnternet
  - Giyinme Odası
  - Gömme Dolap
  - Görüntülü Diafon
  - Hilton Banyo
  - Intercom Sistemi
  - Isıcam
  - Jakuzi
  - Kartonpiyer
  - Kiler
  - Klima
  - Küvet
  - Laminat Zemin
  - Marley
  - Mobilya
  - Mutfak (Ankastre)
  - Mutfak (Laminat)
  - Mutfak Doğalgazı
  - Panjur/Jaluzi
  - Parke Zemin
  - PVC Doğrama
  - Seramik Zemin
  - Set Üstü Ocak
  - Spot Aydınlatma
  - Şofben
  - Şömine
  - Teras
  - Termosifon
  - Vestiyer
  - Wi-Fi
  - Yüz Tanıma & Parmak İzi
  - 24 Saat Güvenlik
  - Buhar Odası
  - Çocuk Oyun Parkı
  - Hamam
  - Hidrofor
  - Isı Yalıtımı
  - Jeneratör
  - Kablo TV
  - Kamera Sistemi
  - Kapıcı
  - Kreş
  - Müstakil Havuzlu
  - Otopark - Açık
  - Otopark - Kapalı
  - Sauna
  - Ses Yalıtımı
  - Siding
  - Spor Alanı
  - Su Deposu
  - Tenis Kortu
  - Uydu
  - Yangın Merdiveni
  - Yüzme Havuzu (Açık)
  - Yüzme Havuzu (Kapalı)
  - Alışveriş Merkezi
  - Belediye
  - Cami
  - Cemevi
  - Denize Sıfır
  - Eczane
  - Eğlence Merkezi
  - Fuar
  - Hastane
  - Havra
  - İlkokul-Ortaokul
  - İtfaiye
  - Kilise
  - Lise
  - Market
  - Park
  - Plaj
  - Polis Merkezi
  - Sağlık Ocağı
  - Semt Pazarı
  - Spor Salonu
  - Şehir Merkezi
  - Üniversite
  - Anayol
  - Avrasya Tüneli
  - Boğaz Köprüleri
  - Cadde
  - Deniz Otobüsü
  - Dolmuş
  - E-5
  - Havaalanı
  - İskele
  - Marmaray
  - Metro
  - Metrobüs
  - Minibüs
  - Otobüs Durağı
  - Sahil
  - Teleferik
  - TEM
  - Tramvay
  - Tren İstasyonu
  - Troleybüs
  - Boğaz
  - Deniz
  - Doğa
  - Göl
  - Havuz
  - Park & Yeşil Alan
  - Şehir
  - Ara Kat
  - Ara Kat Dubleks
  - Bahçe Dubleksi
  - Bahçe Katı
  - Bahçeli
  - Çatı Dubleksi
  - En Üst Kat
  - Forleks
  - Garaj / Dükkan Üstü
  - Giriş Katı
  - Kat Dubleksi
  - Loft
  - Müstakil Girişli
  - Ters Dubleks
  - Tripleks
  - Zemin Kat
  - Araç Park Yeri
  - Banyo
  - Geniş Koridor
  - Giriş / Rampa
  - Merdiven
  - Mutfak
  - Oda Kapısı
  - Priz / Elektrik Anahtarı
  - Tutamak / Korkuluk
  - Tuvalet
  - Yüzme Havuzu